mini/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()
urlpatterns = patterns(
    '',

    # User
    url(r'^$', 'mini.web.views.home.home', name='home'),
    url(r'^user/$', 'mini.web.views.user.register', name='user.register'),
    url(r'^user/(?P<username>\w+)/$', 'mini.web.views.user.read', name='user.read'),
    url(r'^user/(?P<username>\w+)/update', 'mini.web.views.user.update', name='user.update'),
    url(r'^user/(?P<username>\w+)/delete', 'mini.web.views.user.unregister', name='user.delete'),

    # Auth
    url(r'^login', 'mini.web.views.auth.login', name='login'),
    url(r'^logout', 'mini.web.views.auth.logout', name='logout'),

    # Post
    url(r'^post/$', 'mini.web.views.post.write', name='post.write'),
    url(r'^post/(?P<post_id>\d+)/$', 'mini.web.views.post.read', name='post.read'),
    url(r'^user/(?P<username>\w+)/post', 'mini.web.views.post.timeline', name='timeline'),
    url(r'^newsfeed/$', 'mini.web.views.post.newsfeed', name='newsfeed'),
    url(r'^post/(?P<post_id>\d+)/update', 'mini.web.views.post.update', name='post.update'),
    url(r'^post/(?P<post_id>\d+)/delete', 'mini.web.views.post.delete', name='post.delete'),
    url(r'^post/(?P<post_id>\d+)/like', 'mini.web.views.post.like', name='post.like'),

    # Comment
    url(r'^post/(?P<post_id>\d+)/comment/write/$', 'mini.web.views.comment.write', name='comment.write'),
    url(r'^post/(?P<post_id>\d+)/comment/$', 'mini.web.views.comment.read', name='comment.read'),
    url(r'^comment/(?P<comment_id>\d+)/update', 'mini.web.views.comment.update', name='comment.update'),
    url(r'^comment/(?P<comment_id>\d+)/delete', 'mini.web.views.comment.delete', name='comment.delete'),
    url(r'^comment/(?P<comment_id>\d+)/like', 'mini.web.views.comment.like', name='comment.like'),

    # Friend
    url(r'^friendrequest/(?P<to_username>\w+)/$', 'mini.web.views.friend.friend_request', name='friend.request'),
    url(r'^user/(?P<username>\w+)/friend/$', 'mini.web.views.friend.read', name='friend.read'),
    url(r'^friendrequest/$', 'mini.web.views.friend.request_list', name='friend.request_list'),
    url(r'^friend/friendrequest/(?P<from_username>\w+)/$', 'mini.web.views.friend.accept', name='friend.accept'),
    url(r'^friendrequest/(?P<from_username>\w+)/delete', 'mini.web.views.friend.decline', name='friend.decline'),
    url(r'^friendrequest/(?P<to_username>\w+)/cancel', 'mini.web.views.friend.cancel', name='friend.cancel'),
    url(r'^friend/(?P<to_username>\w+)/delete', 'mini.web.views.friend.unfriend', name='friend.delete'),

    # Admin
    url(r'^admin/', include(admin.site.urls)),
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mini/web/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.db.models import Q


class Model(models.Model):
    def __str__(self):
        return str(self.id)

    class Meta(object):
        abstract = True


class MyUser(AbstractUser):
    RELATIONSHIP_STATUSES = (
        ('y', '연애중'),
        ('n', '싱글'),
        ('m', '결혼'),
    )

    relationship_status = models.CharField(max_length=1, null=True, blank=True,
                                           choices=RELATIONSHIP_STATUSES)
    IMAGE_DIR = 'profile-images'
    profile_image = models.ImageField(
        upload_to=IMAGE_DIR, null=False,
        blank=True,
        default=settings.STATIC_URL+'images/default_profile.png')
    birth = models.DateField(null=True, blank=True)
    phone = models.CharField(max_length=11, null=True, blank=True)

    def is_friend_of(self, user):
        friendships = Friend.objects.filter(Q(first_user=self) | Q(second_user=self))
        return friendships.filter(Q(first_user=user) | Q(second_user=user)).exists()

    def sent_request_to(self, user):
        return FriendRequest.objects.filter(from_user=self, to_user=user).exists()


class Post(Model):
    writer = models.ForeignKey(settings.AUTH_USER_MODEL)
    content = models.TextField(null=False)
    created = models.DateTimeField(auto_now_add=True)
    IMAGE_DIR = 'post-images'
    image = models.ImageField(upload_to=IMAGE_DIR, null=True, blank=True)
    likes = models.IntegerField(default=0)


class Comment(Model):
    writer = models.ForeignKey(settings.AUTH_USER_MODEL)
    content = models.TextField(null=False)
    created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post)
    likes = models.IntegerField(default=0)


class Friend(Model):
    first_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='+')
    second_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='+')
    created = models.DateTimeField(auto_now_add=True)


class FriendRequest(Model):
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='+')
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='+')
    accepted = models.DateTimeField(auto_now=True, null=True)
    created = models.DateTimeField(auto_now_add=True)


class PostLike(Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    post = models.ForeignKey(Post)


class CommentLike(Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    comment = models.ForeignKey(Comment)

mini/web/views/user.py
# -*- coding: utf-8 -*-
import functools
from django.template import RequestContext
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render_to_response
from mini.web import forms as f
from mini.web import models as m
from django.contrib.auth.decorators import login_required


@csrf_exempt
def register(request):
    if request.user.is_authenticated():
        return redirect('home')

    ctx = RequestContext(request)
    registered = False

    if request.method == 'POST':
        user_form = f.UserForm(request.POST)

        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()

            registered = True

        else:
            pass

    else:
        user_form = f.UserForm()

    return render_to_response(
        'home.html', {'user_form': user_form, 'registered': registered, 'login_form': f.LoginForm()}, ctx)


@csrf_exempt
@login_required
def unregister(request, username=None):
    request.user.delete()
    return redirect('home')


def read(request, username=None):
    user = m.MyUser.objects.get(username=username)

    if request.user.is_friend_of(user):
        is_friend = True
    else:
        is_friend = False

    if request.user.sent_request_to(user):
        sent_request = True
    else:
        sent_request = False

    return render_to_response('user/profile.html',
                              {'profile': user,
                               'is_friend': is_friend,
                               'sent_request': sent_request}, RequestContext(request))


@csrf_exempt
@login_required
def update(request, username=None):
    ctx = RequestContext(request)
    user = m.MyUser.objects.get(username=username)
    if request.user != user:
        return redirect('home')

    updated = False

    if request.method == 'POST':
        edit_u_form = f.EditUserForm(request.POST, request.FILES, instance=user)

        if edit_u_form.is_valid():
            edit_u_form.save()
            if 'profile_image' not in request.FILES \
                    and user.profile_image is None:
                user.profile_image = 'static/images/default_profile.png'
                user.save()

            updated = True

    else:
        edit_u_form = f.EditUserForm(instance=user)

    if updated:
        return redirect('/user/'+username)

    return render_to_response(
        'user/update.html', {'profile': user, 'edit_u_form': edit_u_form}, ctx)

mini/web/templates/user/profile.html
{% extends "default/base.html" %}
{% load staticfiles %}
{% block style %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'css/user/profile.css' %}"/>
{% endblock style %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/user/profile.js' %}"></script>
{% endblock js %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">
                <div class="panel panel-info">
                    <div class="panel-heading">
                    <div class="row">
                        <div class="col-md-8">
                        <h3 class="panel-title">{{ profile.username }}</h3></div>
                        <div class="col-md-4">
                        {% if profile != user %}
                            {% if is_friend %}
                                <div class="dropdown pull-right">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                    친구
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a role="menuitem" href="{% url 'friend.delete' to_username=profile.username %}">친구 끊기</a></li>
                                </ul>
                                </div>
                            {% elif sent_request %}
                                <form method="POST" action="{% url 'friend.cancel' to_username=profile.username %}">
                                    <button type="submit" class="btn btn-primary pull-right">친구요청 취소</button>
                                </form>
                            {% else %}
                                <form method="POST" action="{% url 'friend.request' to_username=profile.username %}">
                                    <button type="submit" class="btn btn-primary pull-right">친구 요청</button>
                                </form>
                            {% endif %}
                        {% endif %}
                        </div>
                    </div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-3 col-lg-3 " align="center">
                                <p>
                                    <img src="{{ profile.profile_image.url }}" height="100" width="100" class="img-circle"/>
                                </p>

                                <p>
                                    <a href="{% url 'friend.read' username=profile.username %}" class="btn btn-primary mini-profile-btn">Friends</a>
                                </p>

                                <p>
                                    <a href="{% url 'timeline' username=profile.username %}" class="btn btn-primary mini-profile-btn">Posts</a>
                                </p>
                            </div>
                            <div class=" col-md-9 col-lg-9 ">
                                <table class="table table-user-information">
                                    <tbody>
                                    <tr>
                                        <td>E-mail</td>
                                        <td>{{ profile.email }}</td>
                                    </tr>
                                    <tr>
                                        <td>생일</td>
                                        <td>{{ profile.birth }}</td>
                                    </tr>
                                    <tr>
                                        <td>가입일</td>
                                        <td>{{ profile.date_joined }}</td>
                                    </tr>
                                    <tr>
                                        <td>전화번호</td>
                                        <td>{{ profile.phone }}</td>
                                    </tr>
                                    <tr>
                                        <td>상태</td>
                                        <td>{{ profile.get_relationship_status_display }}</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer mini-profile-footer">
                        {% if user == profile %}
                            <span class="pull-right">
                                <a href="{% url 'user.update' username=user.username %}" type="button" class="btn btn-sm btn-warning mini-profile-btn">정보
                                    수정</a>
                                <form class="inline" method="POST" id="mini-form-unregister" action="{% url 'user.delete' username=user.username %}">
                                    <button type="submit" class="btn btn-sm btn-danger mini-profile-btn">
                                        탈퇴
                                    </button>
                                </form>
                            </span>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock main %}

mini/web/templates/user/update.html
{% extends "default/base.html" %}
{% load staticfiles %}
{% block style %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'css/user/profile.css' %}"/>
{% endblock style %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/user/profile.js' %}"></script>
{% endblock js %}


{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{profile.username}}</h3>
                    </div>
                    <form method="post" action="{% url 'user.update' username=profile.username %}" enctype="multipart/form-data" class="form-horizontal" role="form">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-3 col-lg-3 " align="center">
                                    <p><img src="{{ edit_u_form.profile_image.value.url }}" height="100" width="100" class="img-circle"/></p>
                                    <p>{{edit_u_form.profile_image}}</p>
                                </div>
                                <div class=" col-md-9 col-lg-9 ">
                                    <table class="table table-user-information">
                                    <tbody>
                                    <tr>
                                    <td>{{edit_u_form.email.label}}</td>
                                    <td>{{edit_u_form.email}}</td>
                                    </tr>
                                    <tr>
                                    <td>{{edit_u_form.birth.label}}</td>
                                    <td>{{edit_u_form.birth}}</td>
                                    </tr>
                                    <tr>
                                    <td>가입일:</td>
                                    <td>{{profile.date_joined}}</td>
                                    </tr>
                                    <tr>
                                    <td>{{edit_u_form.phone.label}}</td>
                                    <td>{{edit_u_form.phone}}</td>
                                    </tr>
                                    <tr>
                                    <td>{{edit_u_form.relationship_status.label}}</td>
                                    <td>{{edit_u_form.relationship_status}}</td>
                                    </tr>
                                    </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer mini-profile-footer">
                            <span class="pull-right">
                            <button type="submit" name="submit" class="btn btn-sm btn-primary">저장</button>
                            </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}